# Generated by Django 2.1.4 on 2019-02-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190114_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_VIN', models.CharField(max_length=64, unique=True, verbose_name='车辆VIN编码')),
                ('Carname', models.CharField(max_length=24, unique=True, verbose_name='汽车名称')),
                ('License_number', models.CharField(max_length=24, unique=True, verbose_name='车牌号码')),
                ('Serure_number', models.CharField(max_length=128, verbose_name='数据传输验证码')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
