# Generated by Django 2.1.4 on 2019-02-11 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20190211_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrealtimetest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statevehicle', models.CharField(choices=[(0, '启动'), (1, '熄火'), (2, '其他')], max_length=24, verbose_name='车辆状态')),
                ('Chargingstatus', models.CharField(choices=[(0, '停车充电'), (1, '行驶充电'), (2, '未充电'), (3, '充电完成')], max_length=24, verbose_name='充电状态')),
                ('speed', models.FloatField(max_length=48, verbose_name='车速')),
                ('Totalmileage', models.FloatField(max_length=24, verbose_name='累计行程')),
                ('totalvoltage', models.FloatField(max_length=24, verbose_name='总电压')),
                ('totalcurrent', models.FloatField(max_length=24, verbose_name='总电流')),
                ('SOC', models.CharField(max_length=24, verbose_name='SOC')),
                ('DC_DC', models.CharField(choices=[(0, '工作'), (1, '断开')], max_length=24, verbose_name='DC/DC状态')),
                ('gear', models.CharField(max_length=24, verbose_name='档位')),
                ('resistance', models.CharField(max_length=24, verbose_name='绝缘电阻')),
                ('Accelerator', models.CharField(max_length=24, verbose_name='加速踏板行程值')),
                ('brake', models.CharField(max_length=24, verbose_name='制动踏板形成值')),
                ('local_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('Carnickname', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Carformtest', verbose_name='汽车名称')),
            ],
        ),
    ]
