# Generated by Django 2.1.4 on 2019-02-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_motortest1'),
    ]

    operations = [
        migrations.CreateModel(
            name='testcarform',
            fields=[
                ('CarVIN', models.CharField(max_length=64, unique=True, verbose_name='车辆VIN编码')),
                ('Carname', models.CharField(max_length=24, unique=True, verbose_name='车辆名称')),
                ('Licensenumber', models.CharField(max_length=24, unique=True, verbose_name='车牌号码')),
                ('serialnum', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True, verbose_name='内部编号')),
                ('Serurenumber', models.CharField(max_length=128, verbose_name='数据传输验证码')),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='testcarrealtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statevehicle', models.CharField(choices=[('01', '启动'), ('02', '熄火'), ('03', '其他'), ('FE', '异常')], max_length=24, verbose_name='车辆状态')),
                ('Chargingstatus', models.CharField(choices=[('01', '停车充电'), ('02', '行驶充电'), ('03', '未充电'), ('04', '充电完成'), ('FE', '异常')], max_length=24, verbose_name='充电状态')),
                ('carmode', models.CharField(choices=[('01', '纯电'), ('02', '混动'), ('03', '燃油'), ('FE', '异常')], max_length=24, verbose_name='运行模式')),
                ('speed', models.FloatField(max_length=48, verbose_name='车速')),
                ('Totalmileage', models.FloatField(max_length=24, verbose_name='累计行程')),
                ('totalvoltage', models.FloatField(max_length=24, verbose_name='总电压')),
                ('totalcurrent', models.FloatField(max_length=24, verbose_name='总电流')),
                ('SOC', models.CharField(max_length=24, verbose_name='SOC')),
                ('DCDC', models.CharField(choices=[('01', '工作'), ('02', '断开'), ('FE', '异常')], max_length=24, verbose_name='DC/DC状态')),
                ('gear', models.CharField(choices=[('01', 'P挡'), ('02', 'D挡'), ('03', 'R挡'), ('FE', '其他')], max_length=24, verbose_name='档位')),
                ('resistance', models.CharField(max_length=24, verbose_name='绝缘电阻')),
                ('Accelerator', models.CharField(max_length=24, verbose_name='加速踏板行程值')),
                ('brake', models.CharField(choices=[('01', '踩下'), ('02', '空'), ('FE', '其他')], max_length=24, verbose_name='制动踏板形成值')),
                ('local_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, max_length=48, null=True, verbose_name='纬度')),
                ('longitude', models.FloatField(blank=True, max_length=48, null=True, verbose_name='经度')),
                ('serialnum', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.testcarform', verbose_name='内部编号')),
            ],
        ),
    ]
