# Generated by Django 2.1.4 on 2019-02-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_testcarform_testcarrealtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtorque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('01', '耗电'), ('02', '发电'), ('03', '关闭'), ('04', '准备'), ('FE', '异常')], max_length=24, verbose_name='驱动电机状态')),
                ('torquespeed', models.CharField(max_length=24, verbose_name='驱动电机转速')),
                ('torque', models.CharField(max_length=24, verbose_name='驱动电机转矩')),
                ('torquetem', models.CharField(max_length=24, verbose_name='驱动电机温度')),
                ('local_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialnum', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.testcarform', verbose_name='内部编号')),
            ],
        ),
        migrations.CreateModel(
            name='testtorquecontrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controltem', models.CharField(max_length=24, verbose_name='驱动电机控制器温度')),
                ('controlV', models.FloatField(max_length=24, verbose_name='电机控制器输入电压')),
                ('controlA', models.FloatField(max_length=24, verbose_name='电机控制器直流母线电流')),
                ('local_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialnum', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.testcarform', verbose_name='内部编号')),
            ],
        ),
    ]
