# Generated by Django 2.1.4 on 2019-02-22 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_testtorque_testtorquecontrol'),
    ]

    operations = [
        migrations.CreateModel(
            name='testbigv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemnum', models.CharField(max_length=24, verbose_name='最高电压电池子系统号')),
                ('bigbattery', models.CharField(max_length=24, verbose_name='最高电压电池单体代号')),
                ('bigv', models.FloatField(max_length=24, verbose_name='电池单体电压最高值')),
                ('local_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialnum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.testcarform', verbose_name='内部编号')),
            ],
        ),
    ]
