# Generated by Django 2.1.4 on 2019-02-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_testbigv'),
    ]

    operations = [
        migrations.CreateModel(
            name='testbattery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemv', models.FloatField(max_length=24, verbose_name='可充电储能装置电压')),
                ('systema', models.FloatField(max_length=24, verbose_name='可充电储能装置电流')),
                ('batterynum', models.CharField(max_length=24, verbose_name='单体电池总数')),
                ('battery01', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery02', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery03', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery04', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery05', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery06', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery07', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery08', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery09', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery10', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery11', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery12', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('battery13', models.FloatField(max_length=24, verbose_name='单体电池电压')),
                ('local_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialnum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.testcarform', verbose_name='内部编号')),
            ],
        ),
    ]
