# Generated by Django 2.1.4 on 2019-02-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_testbattery'),
    ]

    operations = [
        migrations.CreateModel(
            name='testwarn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnhigh', models.CharField(choices=[('01', '1级故障'), ('02', '2级故障'), ('03', '3级故障'), ('FE', '异常')], max_length=24, verbose_name='最高报警等级')),
                ('warn001', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='温度差异报警')),
                ('warn002', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='电池高温报警')),
                ('warn003', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='车载储能装置类型过压报警')),
                ('warn004', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='车载储能装置类型欠压报警')),
                ('warn005', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='SOC低报警')),
                ('warn006', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='单体电池过压报警')),
                ('warn007', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='单体电池欠压报警')),
                ('warn008', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='SOC过高报警')),
                ('warn009', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='SOC跳变报警')),
                ('warn010', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='可充电储能系统不匹配报警')),
                ('warn011', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='电池单体一致性报警')),
                ('warn012', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='绝缘报警')),
                ('warn013', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='DC-DC温度报警')),
                ('warn014', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='制动系统报警')),
                ('warn015', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='DC-DC状态报警')),
                ('warn016', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='驱动电机控制器温度报警')),
                ('warn017', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='高压互锁状态报警')),
                ('warn018', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='驱动电机温度报警')),
                ('warn019', models.CharField(choices=[('01', '报警'), ('02', '正常'), ('FE', '异常')], max_length=24, verbose_name='车载储能装置类型过充')),
                ('local_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('serialnum', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.testcarform', verbose_name='内部编号')),
            ],
        ),
    ]
