# Generated by Django 2.1.4 on 2019-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_auto_20190223_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='zjgzm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DTC', models.CharField(max_length=24, unique=True, verbose_name='故障代码')),
                ('DTC_explain', models.CharField(max_length=256, verbose_name='故障代码信息')),
                ('local_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
